on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ZIG_VERSION: "0.14.0"
name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Zine
        uses: kristoff-it/setup-zine@v1
        with:
          version: v0.10.4
      - name: Release
        run: zine release
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: jeqo-dev
          directory: ./public

