on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ZIG_VERSION: "0.13.0"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install Zig
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      # Build your website
      - name: Build site
        run: |
          zig build
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: jeqo-dev # e.g. 'my-project'
          directory: zig-out
          customDomain: jeqo.dev
