on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ZIG_VERSION: "0.13.0"
name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Cache Zig dependencies and build artifacts
      - name: Cache Zig dependencies
        uses: actions/cache@v3
        with:
          path: |
            .zig-cache
          key: ${{ runner.os }}-zig-${{ env.ZIG_VERSION }}-${{ hashFiles('build.zig', 'build.zig.zon') }}
          restore-keys: |
            ${{ runner.os }}-zig-${{ env.ZIG_VERSION }}-
            ${{ runner.os }}-zig-
      # Install Zig
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
      # Build your website
      - name: Build site
        run: |
          zig build --release=safe --summary new --verbose
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: jeqo-dev # e.g. 'my-project'
          directory: zig-out

